"""
app/routes/voice_routes.py
───────────────────────────
Generates voice debate audio for a completed evaluation.
Also serves individual audio files.
"""
from __future__ import annotations

import asyncio
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.crud import get_evaluation
from app.db.session import get_db
from app.voice.voice_debate_runner import generate_voice_debate
from app.utils.logging_config import get_logger

router = APIRouter(prefix="/api", tags=["voice"])
logger = get_logger(__name__)
# generate_speech() makes a blocking (synchronous) HTTP call per debate turn.
# Running it directly inside an async route would block the whole event loop —
# every other request (uploads, status polling, etc. for ALL users) would stall
# for the entire duration of TTS generation. Offload it to a thread pool instead,
# the same way the main evaluation pipeline already does.
_executor = ThreadPoolExecutor(max_workers=2)


@router.post("/voice/{evaluation_id}", summary="Generate voice debate audio")
async def generate_voice(evaluation_id: str, db: AsyncSession = Depends(get_db)):
    """
    Generate per-turn audio for a completed evaluation's debate.
    Returns list of turns enriched with audio_url fields.
    """
    ev = await get_evaluation(db, evaluation_id)
    if not ev:
        raise HTTPException(status_code=404, detail="Evaluation not found")
    if ev.status != "complete":
        raise HTTPException(status_code=400, detail="Evaluation not yet complete")
    if not ev.final_report:
        raise HTTPException(status_code=400, detail="No final report found")

    # Reconstruct debate transcript from saved turns
    debate_turns = sorted(ev.debate_turns, key=lambda x: (x.round_number, x.turn_number))

    # Group into rounds
    rounds_map: dict[int, list] = {}
    for turn in debate_turns:
        rounds_map.setdefault(turn.round_number, []).append(turn.turn_data)

    debate_transcript = {
        "rounds": [
            {"round_number": rn, "turns": turns}
            for rn, turns in sorted(rounds_map.items())
        ]
    }

    loop = asyncio.get_event_loop()
    enriched = await loop.run_in_executor(
        _executor, generate_voice_debate, debate_transcript, evaluation_id
    )
    return {
        "evaluation_id": evaluation_id,
        "turns": enriched,
        "total_turns": len(enriched),
        "with_audio": sum(1 for t in enriched if t.get("audio_url")),
    }


@router.get("/audio/{filename}", summary="Serve a generated audio file")
async def serve_audio(filename: str):
    """Serve an audio file generated by TTS."""
    audio_path = Path("data/audio") / filename
    if not audio_path.exists():
        raise HTTPException(status_code=404, detail="Audio file not found")
    return FileResponse(
        str(audio_path),
        media_type="audio/wav",
        headers={"Accept-Ranges": "bytes"},
    )
